name: Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu 18.04 Clang-9",
            os: ubuntu-18.04,
            cc: "clang-9",
            cxx: clang++-9
          }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: |
        # Install latest cmake.
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
          | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
        sudo apt install cmake
        cmake --version

        # Install clang-9 and libc++
        sudo apt-add-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
        sudo apt update
        sudo apt install clang-9 libc++-9-dev libc++abi-9-dev
        clang-9 --version

    - name: Configure
      run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest
