name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      CC: clang-10
      CXX: clang++-10
    steps:
    - uses: actions/checkout@v1

    - name: install
      run: |
        echo "Installing llvm-10"; sudo apt install llvm-10
        echo "Installing clang-tidy-10"; sudo apt install clang-tidy-10
        sudo ln -s /usr/bin/clang-tidy-10 /usr/bin/clang-tidy
        sudo ln -s /usr/bin/llvm-cov-10 /usr/bin/llvm-cov
        sudo ln -s /usr/bin/llvm-profdata-10 /usr/bin/llvm-profdata


    - name: configure
      run: ./scripts/configure.sh --type Debug --sanitize --coverage --tests --lint

    - name: build
      run: ./scripts/build.sh

    - name: test
      run: ./scripts/test.sh
